---
- debug:
    msg: "{{ configs[0] }}"

- name: "Setup Linux"
  include_tasks: "linux/{{ item }}.yml"
  args:
    apply:
      become: true
  when: ansible_distribution | regex_search("Debian|Ubuntu")
  loop:
    - uninstall_applications
    - install_applications
    - ssh_keys
    - set_global_gitignore

- name: "Setup Windows"
  include_tasks: "windows/{{ item }}.yml"
  when: ansible_distribution | regex_search("Windows")
  loop:
    - uninstall_applications
    - install_applications
    - ssh_keys
    - set_global_gitignore
