---
- name: "Setup Linux"
  include_tasks: "linux/{{ item }}.yml"
  when: ansible_distribution | regex_search("Debian|Ubuntu")
  loop: "{{ configurations }}"

- name: "Setup Windows"
  include_tasks: "windows/{{ item }}.yml"
  when: ansible_distribution | regex_search("Windows")
  loop:
    - "{{ configurations }}"
    - clean_desktop.yml
    - uninstall_bloatware.yml
