---
- name: "Setup Linux"
  include_tasks: "linux/{{ item }}.yml"
  when: ansible_distribution | regex_search("Debian|Ubuntu")
  loop: "{{ default_configurations + linux_configurations }}"

- name: "Setup Windows"
  include_tasks: "windows/{{ item }}.yml"
  when: ansible_distribution | regex_search("Windows")
  loop: "{{ default_configurations + windows_configurations }}"
