---
- name: Ensure Anydesk public key is present
  apt_key:
    url: https://keys.anydesk.com/repos/DEB-GPG-KEY

- name: Ensure Anydesk repository in a list
  apt_repository:
    repo: deb http://deb.anydesk.com/ all main
