---
- name: Ensure that dependencies are updated
  become: true
  apt:
    update_cache: true
  changed_when: false

- name: 1. Ensure applications are present
  become: true
  package:
    name: "{{ linux_applications.native }}"

- name: 2. Ensure applications are present
  become: true
  snap:
    name: "{{ linux_applications.snap }}"
    classic: true

- block:
    - name: 3. Ensure apt repository list is update
      include_tasks: anydesk.yml

    - name: 3.1. Ensure applications are present
      become: true
      package:
        name: "{{ linux_applications.ppa }}"

- name: Ensure that dependencies that are no longer required are absent
  become: true
  apt:
    autoclean: true
    autoremove: true
