---
- name: Ensure applications are present
  win_chocolatey:
    name: "{{ windows_applications }}"
    ignore_checksums: true
  retries: 3
  delay: 10
  notify:
    - Reboot the machine with all defaults
