---
- name: Ensure that bloatware uninstalled
  win_shell: iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/Sycnex/Windows10Debloater/master/Windows10SysPrepDebloater.ps1'))
  changed_when: false
