---
windows_applications:
  - 7zip
  - anydesk
  - bitwarden
  - ccleaner
  - chocolateygui
  - clion-ide
  - discord
  - epicgameslauncher
  - filezilla
  - firefox
  - foobar2000
  - git
  - google-backup-and-sync
  - intellijidea-community
  - jetbrainstoolbox
  - notepadplusplus
  - openssh
  - origin
  - qbittorrent
  - rufus
  - slack
  - steam
  - telegram
  - thunderbird
  - totalcommander
  - uplay
  - vlc
  - windirstat

windows_applications_to_uninstall:
  - microsoft.windowscommunicationsapps
  - Microsoft.BingWeather
  - Microsoft.Advertising.Xaml
  - Microsoft.GetHelp
  - Microsoft.Getstarted
  - Microsoft.MSPaint
  - Microsoft.Microsoft3DViewer
  - Microsoft.MicrosoftEdgeToolsClient
  - Microsoft.MicrosoftOfficeHub
  - Microsoft.MicrosoftSolitaireCollection
  - Microsoft.MicrosoftStickyNotes
  - Microsoft.MixedReality.Portal
  - Microsoft.Office.OneNote
  - Microsoft.People
  - Microsoft.Print3D
  - Microsoft.ScreenSketch
  - Microsoft.SkypeApp
  - Microsoft.Wallet
  - Microsoft.Windows.Cortana
  - Microsoft.WindowsAlarms
  - Microsoft.WindowsCamera
  - Microsoft.WindowsFeedbackHub
  - Microsoft.WindowsMaps
  - Microsoft.WindowsSoundRecorder
  - Microsoft.Xbox.TCUI
  - Microsoft.XboxApp
  - Microsoft.XboxGamingOverlay
  - Microsoft.XboxIdentityProvider
  - Microsoft.XboxSpeechToTextOverlay
  - Microsoft.YourPhone
  - Microsoft.ZuneMusic
  - Microsoft.ZuneVideo
