---
windows_applications:
  - 7zip
  - anydesk
  - bitwarden
  - ccleaner
  - chocolateygui
  - clion-ide
  - discord
  - epicgameslauncher
  - filezilla
  - firefox
  - foobar2000
  - git
  - google-backup-and-sync
  - intellijidea-community
  - jetbrainstoolbox
  - notepadplusplus
  - openssh
  - origin
  - powertoys
  - qbittorrent
  - rufus
  - slack
  - steam
  - telegram
  - thunderbird
  - totalcommander
  - uplay
  - vlc
  - windirstat
