---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  yamllint --config-file=molecule/.yamllint.yml .
  ansible-lint .

provisioner:
  name: ansible
  playbooks:
    converge: ../shared/converge.yml
  config_options:
    defaults:
      vault_password_file: "~/ansible_vault_password_file"

scenario:
  test_sequence:
    - lint
    - syntax
    - create
    - converge
    - idempotence
    - destroy
