prepare-environment:
  stage: environment
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo ${CI_REGISTRY_PASSWORD} | docker login --username ${CI_REGISTRY_USER} ${CI_REGISTRY} --password-stdin
    - docker pull ${CI_REGISTRY_IMAGE} || true
    - docker build --tag=${CI_REGISTRY_IMAGE} --cache-from=${CI_REGISTRY_IMAGE} ./.gitlab
    - docker push "${CI_REGISTRY_IMAGE}"
